# Generated by Django 3.1.4 on 2020-12-23 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quizattemptinfo_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattemptinfo',
            name='question',
        ),
        migrations.AddField(
            model_name='quizattemptinfo',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
            preserve_default=False,
        ),
    ]
